apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: euler-copilot
data:
  .env: |
    #配置文件，参考deploy/prod/.env.example
#  dhparam.pem: | #SSL秘钥协商配置文件
#    -----BEGIN DH PARAMETERS-----
#    MIICCAKCAgEA29KHqU1FaHYwJkQiPjpKV7bCV3cV6dvMtRpr1g3I6Q7AcDUGEDk0
#    1XV01HWJShymeN2WuKkLR28Es6N9kvu/3t3Po+PagHNXJg7RTlPgyeOM/dckUiWe
#    86+CpRM8iHKkgoh2JARswTVRHmiwBcVK/GDL2cPTT6Q3YihZZg4GIcIxqQ2Pn8EF
#    ZH3XkLiaOqQpfUF/j20qhi4n8/Zktb3EIJxxBHk06cWVaGvClv6uN6trxIp65Kk5
#    SMMeG//AulZ08Wj4tCqWnktn1ZqfgBXBPB0nSankMHVz2iX8dSJerST8BUPo56VB
#    9eimEKR19Em7hCJOZrl8rBwkZy2w8LFz0UDNaDRLqL+X16KszwRYKmNtEQKwJOjT
#    qWJV0UAUAjPkTbvbtzK0JANT+EWvaESjsmh05+Y5Ezoi69422FNfKhxi4veUN8A+
#    Gfvqve+lqUTwiWESh6zmNpFn4ifvJQZc+QeNUYUSAoYz4n5rKP7CL9rBql2PMSqV
#    QSc9gG/mhSXrgFPM7kN8lG5QUzj78Ove0+DwKD7agMIKS5RI3e8ecmq8XNtLecLW
#    iU/UMbwLsmNzhV6tL0YoMHmkqHfPHyBAbzK9Pk5TG3MPcCE4Sb8TkO1TR3blWbcC
#    xU09fcDYBfNsH6B8MngEAxtXTLTORwJZVpt1k0rl607WnoXIGXBpQqsCAQI=
#    -----END DH PARAMETERS-----
  server.crt: |
    #SSL证书
  server.key: |
    #SSL私钥
  pass.txt: |
    #SSL私钥密码